In [28]:
import pandas as pd
diagnosed_users = pd.read_csv('data/metadata/majority-vote-reddit-metadata.csv')
posts = pd.read_csv('data/posts/v1/reddit-preprocessed.csv')
diagnosed_users = diagnosed_users.drop(columns=['platform'])
posts = posts.drop(columns=['Unnamed: 0'])
display(diagnosed_users.head(2))
display(posts.head(2))

,id,text,author,created_utc,subreddit,is_comment,diagnosis
0,10015uu,كشخص مصاب بإكتئاب حاد (حقيقى مش حوار) وداخل ع...,Zealousideal-Walk939,2023-01-01 17:56:30+00:00,Egypt,True,depression
1,100foy1,السبب الاول: الفلوس\n\n\nالسبب الثاني: ماني جا...,abetterme1,2023-01-01 12:19:02+00:00,saudiarabia,True,depression

,user_id,class,text
0,No_Entry_2175,adhd,الله عليك يا عبغفور ماشي بمبدا معنديش حاجة اخس...
1,Mysterious-Pace-5657,bpd,غلط عن غلط يفرق الضرب والتعنيف من المحرمات في ...

In [29]:
display(diagnosed_users.describe(include='all'))
display(posts.describe(include='all'))

,id,text,author,created_utc,subreddit,is_comment,diagnosis
count,6753,6631,6753,6753,6753,6753,6753
unique,6753,6409,4959,6752,50,2,13
top,10015uu,اولا جمعة مباركة عليكم، اللهم صل وسلم على محمد...,Business_Thing875,2025-09-14 20:38:00+00:00,AlexandriaEgy,True,depression
freq,1,8,61,2,1333,3733,2728

        user_id    class                                               text
count   1115379   928981                                            1115379
unique     9149       19                                            1068978
top     Silll9s  control  اتمني النهارده كان حلو بالنسبه لك و زي كل يوم ...
freq       2303   264469                                                 72

In [30]:
display(diagnosed_users['diagnosis'].value_counts())
# count unique uesers per class in the posts dataset
for c in posts['class'].unique():
    print(f'Num users in class {c}: {posts[posts['class'] == c]['user_id'].nunique()}')

diagnosis
depression         2728
anxiety             955
adhd                830
ocd                 550
sleep_disorder      448
autism              296
panic               203
bipolar             177
ptsd                161
bpd                 136
suicidal            110
schizophrenia        96
eating_disorder      63
Name: count, dtype: int64

Num users in class adhd: 643
Num users in class bpd: 98
Num users in class depression: 1831
Num users in class control: 4080
Num users in class panic: 147
Num users in class sleep_disorder: 357
Num users in class ocd: 311
Num users in class schizophrenia: 45
Num users in class autism: 227
Num users in class anxiety: 644
Num users in class nan: 0
Num users in class ptsd: 92
Num users in class suicidal: 80
Num users in class eating_disorder: 41
Num users in class bipolar: 76
Num users in class narcissistic_pd: 3
Num users in class paranoid_pd: 24
Num users in class trichotillomania: 9
Num users in class did: 11
Num users in class avoidant_pd: 3

In [34]:
print(f'Diagnosed users: {diagnosed_users['author'].nunique()}')
print(f'Posts users: {posts[posts['class'] != 'control']['user_id'].nunique()}')
# missing users in posts dataset

missing_users = set(diagnosed_users['author'].unique()) - set(posts[posts['class'] != 'control']['user_id'].unique())
print(f'Missing users: {len(missing_users)}')
missing_users

Diagnosed users: 4959
Posts users: 5402
Missing users: 106

{'0mo06_',
 '3m_Armoty',
 '7je_0',
 'Amazing-Answer-5639',
 'AndrewHany08',
 'Appropriate_Fox_7322',
 'Bedo20056',
 'Big-Championship7536',
 'BravePerformance6167',
 'Brave_Bumblebee_4056',
 'Budget_Deer_67',
 'CherryEllla',
 'Clear_Historian8551',
 'Commercial-Phase8377',
 'Consistent_Turn7964',
 'Dependent_Pie4078',
 'EmbarrassedSoil8218',
 'Evening_Meet7216',
 'Extension_Review596',
 'Familiar-Health-8418',
 'Federal-Election6060',
 'Formal_Discipline585',
 'Fun-Vehicle3581',
 'FunDrag7212',
 'Guilty_Race2932',
 'Hkmao',
 'Hopeful_Reserve6277',
 'Hour-Management-1679',
 'IStoppedNamingThings',
 'ImaginaryFlatworm796',
 'Intelligent_Owl_3841',
 'Just-Artichoke4267',
 'LILKAYYYY99',
 'Lopsided_Trick_8500',
 'Mammoth-Appeal5016',
 'MohamedAkm0',
 'Mohammed00900',
 'Necessary_Air7147',
 'Novel-Caterpillar-46',
 'Ok-Marionberry-2939',
 'Ok_Picture_5229',
 'Ok_Sorbet9253',
 'Omsd3364',
 'Osos513',
 'Own-Door5373',
 'Positive_Fold_8780',
 'Prior_Soft_543',
 'Puzzleheaded-Fun9828',
 'Qmrss2',
 'RatLord445',
 'RemarkableLimit4079',
 'Responsible-Quote130',
 'Reyeishere',
 'Rude-Masterpiece7154',
 'Salah_kh-22',
 'SaltPractical5265',
 'Seabound97',
 'Sergio-Aguero2005',
 'Sham_135',
 'Shattered-broken',
 'Shehata_prproj',
 'Southern-Plastic-644',
 'Spare_Machine9853',
 'Strange-Outside-7847',
 'Sufficient-Dingo5772',
 'Sufficient-Search-7',
 'Sweet_Original5093',
 'TaroOrganic1191',
 'Temporary_Process_27',
 'ThickAppeal9638',
 'TypicalEgyptian',
 'UniversityOk8603',
 'Unlucky_Exam101',
 'Western_Pickle_1319',
 '[deleted]',
 'anon_x13',
 'asecretsgonnakillme',
 'curiouscupcake22',
 'cyborg_ghost',
 'emotional_neko',
 'encapsula',
 'fatherofth',
 'ger0_0ges',
 'guyneedHelp3285',
 'hunter69240',
 'imscaredo',
 'kossomhyaty',
 'kurtmoody21',
 'line_takmu999',
 'maro-xx11',
 'maryoma2006',
 'memyselfishself',
 'moaemen',
 'oab1990',
 'realmanzayn',
 'ro6septic',
 'saltylee3004',
 'sleeplesshed',
 'sonzai_re12',
 'ssrt_',
 'suscraftx',
 'themightyNA',
 'unstable_frogg',
 'wandererinhisownsoul',
 'xxxtentacioo',
 'yassinovesky'}